### ISSUE TITLE
Mögliche Verlinkung

### ISSUE THREAD

**Issue by witto13** [nvegater/gridlink#51]
![Image](https://github.com/nvegater/gridlink/assets/161077841/18958e6c-e4a7-4827-9384-63aab60ab978)

Aqui me di cuenta que tenemos un problema. Es lo que te conte en el cine. En teoría las dos compañías siempre tienen la opción de decidir con quien hacen la verlinkung, por eso tenemos mögliche Verlinkung. Cuando uno de las dos compañías llena el formulario, la otra compañía ya no tiene ese mögliche Verlinkung, sino una Verlinkung en estado rojo. El problema es que la compañía que tiene el estado rojo no sabe con quien es la mögliche verlinkung, entonces eso puede ser un problema. Mi solución rápida y buena es mantener toda la lógica, pero solo cambia la información que tenemos en la caja con el estado rojo. La idea es poner la misma información de la mögliche Verlinkung en esa misma caja, así:

![Image](https://github.com/nvegater/gridlink/assets/161077841/c5b96ccc-ce2a-4454-b055-b5283dc2f3bd)

**Comment by nvegater** [comment]
Dale suena bien. Entonces añado esa info al proyecto.
